#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-ggrepel
Version  : 0.9.1
Release  : 3
URL      : https://cran.r-project.org/src/contrib/ggrepel_0.9.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ggrepel_0.9.1.tar.gz
Summary  : Automatically Position Non-Overlapping Text Labels with
Group    : Development/Tools
License  : GPL-3.0
Requires: R-ggrepel-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-ggplot2
Requires: R-rlang
Requires: R-scales
BuildRequires : R-Rcpp
BuildRequires : R-ggplot2
BuildRequires : R-gridExtra
BuildRequires : R-rlang
BuildRequires : R-scales
BuildRequires : buildreq-R

%description
overlapping text labels. Labels repel away from each other and away from the
    data points.

%package lib
Summary: lib components for the R-ggrepel package.
Group: Libraries

%description lib
lib components for the R-ggrepel package.


%prep
%setup -q -c -n ggrepel
cd %{_builddir}/ggrepel

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641027166

%install
export SOURCE_DATE_EPOCH=1641027166
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ggrepel
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ggrepel
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ggrepel
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc ggrepel || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ggrepel/DESCRIPTION
/usr/lib64/R/library/ggrepel/INDEX
/usr/lib64/R/library/ggrepel/LICENSE
/usr/lib64/R/library/ggrepel/Meta/Rd.rds
/usr/lib64/R/library/ggrepel/Meta/features.rds
/usr/lib64/R/library/ggrepel/Meta/hsearch.rds
/usr/lib64/R/library/ggrepel/Meta/links.rds
/usr/lib64/R/library/ggrepel/Meta/nsInfo.rds
/usr/lib64/R/library/ggrepel/Meta/package.rds
/usr/lib64/R/library/ggrepel/Meta/vignette.rds
/usr/lib64/R/library/ggrepel/NAMESPACE
/usr/lib64/R/library/ggrepel/NEWS.md
/usr/lib64/R/library/ggrepel/R/ggrepel
/usr/lib64/R/library/ggrepel/R/ggrepel.rdb
/usr/lib64/R/library/ggrepel/R/ggrepel.rdx
/usr/lib64/R/library/ggrepel/doc/ggrepel.R
/usr/lib64/R/library/ggrepel/doc/ggrepel.Rmd
/usr/lib64/R/library/ggrepel/doc/ggrepel.html
/usr/lib64/R/library/ggrepel/doc/index.html
/usr/lib64/R/library/ggrepel/help/AnIndex
/usr/lib64/R/library/ggrepel/help/aliases.rds
/usr/lib64/R/library/ggrepel/help/figures/ggrepel-allison_horst.jpg
/usr/lib64/R/library/ggrepel/help/figures/logo.svg
/usr/lib64/R/library/ggrepel/help/ggrepel.rdb
/usr/lib64/R/library/ggrepel/help/ggrepel.rdx
/usr/lib64/R/library/ggrepel/help/paths.rds
/usr/lib64/R/library/ggrepel/html/00Index.html
/usr/lib64/R/library/ggrepel/html/R.css
/usr/lib64/R/library/ggrepel/tests/testthat.R
/usr/lib64/R/library/ggrepel/tests/testthat/test-grob-order.R
/usr/lib64/R/library/ggrepel/tests/testthat/test-lots-of-points.R
/usr/lib64/R/library/ggrepel/tests/testthat/test-seed.R
/usr/lib64/R/library/ggrepel/tests/testthat/test-to_unit.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/ggrepel/libs/ggrepel.so
/usr/lib64/R/library/ggrepel/libs/ggrepel.so.avx2
/usr/lib64/R/library/ggrepel/libs/ggrepel.so.avx512
