#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: ab27b0e
#
Name     : R-ggrepel
Version  : 0.9.5
Release  : 15
URL      : https://cran.r-project.org/src/contrib/ggrepel_0.9.5.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ggrepel_0.9.5.tar.gz
Summary  : Automatically Position Non-Overlapping Text Labels with
Group    : Development/Tools
License  : GPL-3.0
Requires: R-ggrepel-lib = %{version}-%{release}
Requires: R-ggrepel-license = %{version}-%{release}
Requires: R-Rcpp
Requires: R-ggplot2
Requires: R-rlang
Requires: R-scales
Requires: R-withr
BuildRequires : R-Rcpp
BuildRequires : R-ggplot2
BuildRequires : R-rlang
BuildRequires : R-scales
BuildRequires : R-vdiffr
BuildRequires : R-withr
BuildRequires : buildreq-R

%description
overlapping text labels. Labels repel away from each other and away from the
    data points.

%package lib
Summary: lib components for the R-ggrepel package.
Group: Libraries
Requires: R-ggrepel-license = %{version}-%{release}

%description lib
lib components for the R-ggrepel package.


%package license
Summary: license components for the R-ggrepel package.
Group: Default

%description license
license components for the R-ggrepel package.


%prep
%setup -q -n ggrepel
pushd ..
cp -a ggrepel buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1704989016

%install
export SOURCE_DATE_EPOCH=1704989016
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-ggrepel
cp %{_builddir}/ggrepel/LICENSE %{buildroot}/usr/share/package-licenses/R-ggrepel/12d81f50767d4e09aa7877da077ad9d1b915d75b || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ggrepel/DESCRIPTION
/usr/lib64/R/library/ggrepel/INDEX
/usr/lib64/R/library/ggrepel/LICENSE
/usr/lib64/R/library/ggrepel/Meta/Rd.rds
/usr/lib64/R/library/ggrepel/Meta/features.rds
/usr/lib64/R/library/ggrepel/Meta/hsearch.rds
/usr/lib64/R/library/ggrepel/Meta/links.rds
/usr/lib64/R/library/ggrepel/Meta/nsInfo.rds
/usr/lib64/R/library/ggrepel/Meta/package.rds
/usr/lib64/R/library/ggrepel/Meta/vignette.rds
/usr/lib64/R/library/ggrepel/NAMESPACE
/usr/lib64/R/library/ggrepel/NEWS.md
/usr/lib64/R/library/ggrepel/R/ggrepel
/usr/lib64/R/library/ggrepel/R/ggrepel.rdb
/usr/lib64/R/library/ggrepel/R/ggrepel.rdx
/usr/lib64/R/library/ggrepel/doc/ggrepel.R
/usr/lib64/R/library/ggrepel/doc/ggrepel.Rmd
/usr/lib64/R/library/ggrepel/doc/ggrepel.html
/usr/lib64/R/library/ggrepel/doc/index.html
/usr/lib64/R/library/ggrepel/help/AnIndex
/usr/lib64/R/library/ggrepel/help/aliases.rds
/usr/lib64/R/library/ggrepel/help/figures/logo.svg
/usr/lib64/R/library/ggrepel/help/ggrepel.rdb
/usr/lib64/R/library/ggrepel/help/ggrepel.rdx
/usr/lib64/R/library/ggrepel/help/paths.rds
/usr/lib64/R/library/ggrepel/html/00Index.html
/usr/lib64/R/library/ggrepel/html/R.css
/usr/lib64/R/library/ggrepel/tests/testthat.R
/usr/lib64/R/library/ggrepel/tests/testthat/test-grob-order.R
/usr/lib64/R/library/ggrepel/tests/testthat/test-just-with-angle.R
/usr/lib64/R/library/ggrepel/tests/testthat/test-lots-of-points.R
/usr/lib64/R/library/ggrepel/tests/testthat/test-seed.R
/usr/lib64/R/library/ggrepel/tests/testthat/test-to_unit.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/ggrepel/libs/ggrepel.so
/usr/lib64/R/library/ggrepel/libs/ggrepel.so.avx2
/usr/lib64/R/library/ggrepel/libs/ggrepel.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-ggrepel/12d81f50767d4e09aa7877da077ad9d1b915d75b
